### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by jerrenss** [NUS-Fintech-Society/SD_Fintech_Website#102]
![image](https://user-images.githubusercontent.com/50544486/149667460-d8a98027-7f36-4e99-a947-4d7a40aedfa7.png)

Add this Footer to the Layout Component

**Comment by ivanderjmw** [comment]
<img width="1439" alt="Screenshot 2022-01-22 at 4 30 14 PM" src="https://user-images.githubusercontent.com/57558909/150631054-367bc1a1-9613-49ed-94e9-e4065429d4d5.png">
Should this old footer be replaced then?

**Comment by jerrenss** [comment]
> <img alt="Screenshot 2022-01-22 at 4 30 14 PM" width="1439" src="https://user-images.githubusercontent.com/57558909/150631054-367bc1a1-9613-49ed-94e9-e4065429d4d5.png">
> Should this old footer be replaced then?

Yup, lets use the dark blue footer instead. Just gotta add it to the staging site

**Comment by ivanderjmw** [comment]
Just assigned to @jianoway, should be pretty clear -- just remember we are starting new in the staging branch :)
