### ISSUE TITLE
[EP-2] Change css of "Our Team" section to have max-width

### ISSUE THREAD

**Issue by Wincenttjoi** [NUS-Fintech-Society/SD_Fintech_Website#36]
Content is too large when it is in full screen mode, especially in ultrawide monitors.

Change purpose and goal colour scheme (only need to work on this once design is finalised)

**Comment by jerrenss** [comment]
Add max width to the 4 pages in Our Team. Can consider using Material UI's <Container maxwidth='lg'/> element.

https://mui.com/api/container/
