### ISSUE TITLE
[EP-2] Fix sending email feature

### ISSUE THREAD

**Issue by Wincenttjoi** [NUS-Fintech-Society/SD_Fintech_Website#37]
Sending email is not working.

Add on feature: (to be implemented in the future)
- [ ] Show a dialog / notification to user when it has email successfully been sent (or failed)

**Comment by jerrenss** [comment]
Currently, API only saves form's data into database. There is no function to deliver it to email. Might need to explore ways to integrate email sending function, such as using Formspree.
