### ISSUE TITLE
Club Structure and Our Teams components

### ISSUE THREAD

**Issue by jerrenss** [NUS-Fintech-Society/SD_Fintech_Website#95]
![image](https://user-images.githubusercontent.com/50544486/149666909-3ede4bfd-6cfe-4d66-93f6-6cdff142026d.png)

**Comment by zzhikai** [comment]
To clarify, this is implementation of Club Structure Section above Our Teams and Our Team Section no change required right.

**Comment by jerrenss** [comment]
> To clarify, this is implementation of Club Structure Section above Our Teams and Our Team Section no change required right.

Yup! Our Teams no change from the one in production
