### ISSUE TITLE
Courses Page

### ISSUE THREAD

**Issue by jerrenss** [NUS-Fintech-Society/SD_Fintech_Website#97]
![image](https://user-images.githubusercontent.com/50544486/149666988-b2404f75-2607-41ce-ae41-014e5f96b84c.png)

Courses and Events should share the same Card component

**Comment by ivanderjmw** [comment]
I assume this needs to also be mapped from JSON?

**Comment by jerrenss** [comment]
Yup! Can mock the JSON data in /data folder for a start

> I assume this needs to also be mapped from JSON?
