### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by jerrenss** [NUS-Fintech-Society/SD_Fintech_Website#98]
![image](https://user-images.githubusercontent.com/50544486/149667039-a3b6dd7d-e5fe-4982-a470-54d4ba5edfe3.png)

Will need an external library to implement the calendar page. This should allow maintainers to maintain the events through a list of JSON data similar to previous approach. Can share the same Card component as Courses page.

**Comment by ivanderjmw** [comment]
<img width="1431" alt="Screenshot 2022-01-22 at 8 18 44 PM" src="https://user-images.githubusercontent.com/57558909/150638288-bb87e328-6a24-4743-862a-708d46db7750.png">
Just an in progress update.

**Comment by jerrenss** [comment]
> <img alt="Screenshot 2022-01-22 at 8 18 44 PM" width="1431" src="https://user-images.githubusercontent.com/57558909/150638288-bb87e328-6a24-4743-862a-708d46db7750.png">
> Just an in progress update.

Looks great! Just rmb to make changes on a feature branch off stg, as the theming has been set up already 👍

**Comment by ivanderjmw** [comment]
Assigned to @jianoway -- but since I am in charge of the cards, he can focus on the calendar (I was still using the old one)

Gonna post some library reccs for the calendar soon

**Comment by ivanderjmw** [comment]
Library recommendations:
- react-big-calendar
- fullcalendar
I will use react-big-calendar since it has the most extensive features for free, this also mean I can port in some of the features.
